### ISSUE TITLE
require('array-to-sentence') not working

### ISSUE THREAD

**Issue by sadranyi** [shinnn/array-to-sentence#2]
how do you include it to your project after you npm install it

**Comment by shinnn** [comment]
`require('array-to-sentence')` just works. For example [`array-to-error`](https://github.com/shinnn/array-to-error) [depends on `array-to-sentence`](https://github.com/shinnn/array-to-error/blob/2002ec486b8d4b79a0b8ebe5a12c3db22136721d/index.js#L7) and it [passes all the tests](https://travis-ci.org/shinnn/array-to-error/builds/157042962).
